AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sns-sqs-topic

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: sns-sqs-queue

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSTopic
      Endpoint: !GetAtt SQSQueue.Arn

Outputs:
  SNSTopicArn:
    Description: The ARN of the SNS topic
    Value: !Ref SNSTopic

  SQSQueueArn:
    Description: The ARN of the SQS queue
    Value: !GetAtt SQSQueue.Arn
